language: php

php:
  - 5.5
  - 5.4
  - 5.3

notifications:
  email:
    - me@amcgowan.ca

mysql:
  database: myprofile
  username: root
  encoding: utf8

before_install:
  - "pwd"
  - "sudo apt-get update"
  - "wget http://imgurl.com/tools/imgurbash.sh -O $TRAVIS_BUILD_DIR/imgurbash.sh && chmod +x $TRAVIS_BUILD_DIR/imgurbash.sh"

before_script:
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql php5-curl
  - sudo sed -i -e "s,/var/www,$(pwd)/packaged,g" /etc/apache2/sites-available/default
  - sudo a2enmod rewrite
  - sudo a2enmod actions
  - sudo service apache2 restart
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - drush make build-my_profile.make packaged --no-cache --no-gitinfofile --yes
  - cd packaged
  - drush site-install my_profile --account-name=admin --account-pass=password --account-mail=admin@localhost.com --site-mail=admin@localhost.com --site-name=MyProfile --db-url=mysql://root@localhost/myprofile --yes
  - drush fra --yes
  - drush cc all
  - drush php-eval 'print "Webform Module Exists: " . (module_exists("webform") ? "Yes" : "No") . PHP_EOL;'
  - cd ..
  - curl localhost
  - time curl http://localhost -s -o /dev/null

after_failure:
  - ls -lash $TRAVIS_BUILD_DIR/fail*.png
  - $TRAVIS_BUILD_DIR/imgurbash.sh $TRAVIS_BUILD_DIR/fail*.png
